name: Second CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
        - name: Say Hello
          run: echo "Hello from the second workflow!"
  test:
    runs-on: ubuntu-latest
    needs: build

    steps: 
        - name: Say Hello
          run: echo "test completed successfully!"